name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install NPM dependencies
        run: npm install

      - name: Build Web App
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Capacitor Add Android
        run: |
          npx cap add android
          npx cap sync android

      - name: Inject Deep Link for Website
        run: |
          sed -i '/<\/activity>/i \
                <intent-filter android:autoVerify="true"> \
                    <action android:name="android.intent.action.VIEW" /> \
                    <category android:name="android.intent.category.DEFAULT" /> \
                    <category android:name="android.intent.category.BROWSABLE" /> \
                    <data android:scheme="http" android:host="ainelhadjelstore.kesug.com" /> \
                    <data android:scheme="https" android:host="ainelhadjelstore.kesug.com" /> \
                </intent-filter>' android/app/src/main/AndroidManifest.xml

      - name: Generate App Icons (If assets/icon.png exists)
        run: |
          if [ -f "assets/icon.png" ]; then
            npx @capacitor/assets generate --android
          else
            echo "No assets/icon.png found. Skipping icon generation."
          fi

      - name: Build APK
        working-directory: ./android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AinElHadjelStore.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
